export const ORDER_CREATE_REQUEST = 'ORDER_CREATE-REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE-SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE-FAIL'

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS-REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS-SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS-FAIL'
